- package.json
- src/web_player.js
- test/embedded-player.test.js
https://github.com/ant-media/Ant-Media-Server/issues/6062
> Fix the trailer slash and no port issue

- .github/workflows/publish-snapshot.yml
- src/web_player.js
- test/embedded-player.test.js
https://github.com/ant-media/Ant-Media-Server/issues/6030
> Auto play with sound if Media Engagement Index is crossed

- .github/workflows/run-tests.yml
- src/web_player.js
- test/embedded-player.test.js
https://github.com/ant-media/Ant-Media-Server/issues/6030
> Handle playback_not_allowed error in dash player

- package-lock.json
- package.json
- rollup.config.module.cjs
- src/web_player.js
- test/embedded-player.test.js
- tsconfig.json
https://github.com/ant-media/Ant-Media-Server/issues/6548
First this needs to be merged:
https://github.com/ant-media/videojs-webrtc-plugin/pull/26
> ll-hls support

- src/web_player.js
https://github.com/ant-media/Ant-Media-Server/issues/6643
> Add mp3 to supported formats

- package.json
- rollup.config.module.cjs
- src/web_player.js
- test/embedded-player.test.js
- tsconfig.json
https://github.com/ant-media/Ant-Media-Server/issues/6424
> Increase the wait time of resolution change process

- package.json
> update new version test

- package.json
> test update version

- package.json
> update version test

- package.json
revert version to correct latest
> revert version to correct latest

- src/web_player.js
- test/embedded-player.test.js
https://github.com/ant-media/Ant-Media-Server/issues/6702
Supported events:
```
[
'abort',
'canplay',
'canplaythrough',
'durationchange',
'emptied',
'ended',
'error',
'loadeddata',
'loadedmetadata',
'loadstart',
'pause',
'play',
'playing',
'progress',
'ratechange',
'seeked',
'seeking',
'stalled',
'suspend',
'timeupdate',
'volumechange',
'waiting',
'enterpictureinpicture',
'leavepictureinpicture',
'fullscreenchange',
'resize',
'audioonlymodechange',
'audiopostermodechange',
'controlsdisabled',
'controlsenabled',
'debugon',
'debugoff',
'disablepictureinpicturechanged',
'dispose',
'enterFullWindow',
'error',
'exitFullWindow',
'firstplay',
'fullscreenerror',
'languagechange',
'loadedmetadata',
'loadstart',
'playerreset',
'playerresize',
'posterchange',
'ready',
'textdata',
'useractive', …
```
> Listen player events

- src/web_player.js
- Allowing users to set the **controls** of web player.
> videojs-controls, based on user selection

- .github/workflows/publish-snapshot.yml
- src/web_player.js
- test/embedded-player.test.js
https://github.com/ant-media/Ant-Media-Server/issues/3917
> Support backup stream in web player

- src/web_player.js
https://github.com/ant-media/Ant-Media-Server/issues/6899
> Fix PTZ buttons src address

- src/web_player.js
- test/embedded-player.test.js
https://github.com/ant-media/Ant-Media-Server/issues/7152
> Fix xhr API to append tokens

- src/web_player.js
https://github.com/ant-media/Ant-Media-Server/issues/7152
> Fix getting this context

- package.json
- src/web_player.js
- test/embedded-player.test.js
https://github.com/ant-media/Ant-Media-Server/issues/6972
> make auto start on demand faster

- test/embedded-player.test.js
https://github.com/ant-media/Ant-Media-Server/issues/6972
> Fix backup stream

- src/web_player.js
Related issue: https://github.com/ant-media/Ant-Media-Server/issues/7258
Related PR: https://github.com/ant-media/Ant-Media-Management-Console/pull/273
Related PR: https://github.com/ant-media/ant-media-documentation/pull/548
> SubFolders if specified in URL for WebRTC and DASH streams will now be ignored

- src/web_player.js
https://github.com/ant-media/Ant-Media-Server/issues/7413
> Add withCredentials option

- test/embedded-player.test.js
https://github.com/ant-media/Ant-Media-Server/issues/7413
> add test cases for with withCredentials
